Repository ucsb-cs156-s23/proj-gauchoride-s23-5pm-1, pull requests merged in 2023-06, with the labels that each got.

#25 James rider toggle button
  frontend/src/fixtures/usersFixtures.js
  frontend/src/main/components/Users/UsersTable.js
  frontend/src/tests/pages/AdminUsersPage.test.js
Labels: 10

#31 cf - Added a blue color to the navbar
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
Labels: 5

#42 ve- added RideForm, RideForm stories, RideForm test and rideFixtures
  frontend/src/fixtures/rideFixtures.js
  frontend/src/main/components/Ride/RideForm.js
  frontend/src/stories/components/Ride/RideForm.stories.js
  frontend/src/tests/components/Ride/RideForm.test.js
Labels: 10

#47 Vikram ride create page
  frontend/src/App.js
  frontend/src/fixtures/rideFixtures.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/components/Ride/RideForm.js
  frontend/src/main/pages/Ride/RideCreatePage.js
  frontend/src/stories/pages/Ride/RideCreatePage.stories.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/Ride/RideCreatePage.test.js
Labels: 10, Merge Candidate-CI/CD
