Repository ucsb-cs156-s23/proj-gauchoride-s23-5pm-1, pull requests merged in 2023-05, with the labels that each got.

#5 ef - add POST endpoint for toggle driver
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/UsersController.java
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/UsersControllerTests.java
Labels: 10

#10 jt- added rider member var in user class
  frontend/package-lock.json
  frontend/src/main/components/Users/UsersTable.js
  src/main/java/edu/ucsb/cs156/gauchoride/entities/User.java
Labels: INSTUCTOR: assign points

#20 cf - added a toggleDriver button to UsersTable.js
  frontend/src/main/components/Users/UsersTable.js
  frontend/src/tests/pages/AdminUsersPage.test.js
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/UsersControllerTests.java
Labels: INSTUCTOR: assign points

#14 Added new home page
  frontend/public/UCSBLogo.png
  frontend/src/main/pages/HomePage.js
Labels: 5

#33 pc - update workflow 33 to publish stryker report even if coverage is below 100%
  .github/workflows/33-frontend-pr-mutation-testing.yml
Labels: staff
